// <auto-generated />
using System;
using HRIS.Basic.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRIS.Basic.Migrations.HrisDbRev
{
    [DbContext(typeof(HrisDbRevContext))]
    partial class HrisDbRevContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRIS.Basic.Models.Domain.Employee", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Cnic")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CompanyEmailAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<Guid>("EmployeeRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmploymentStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("date");

                    b.Property<string>("PersonalEmailAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EmployeeId")
                        .HasName("PK_Employee_1");

                    b.HasIndex("EmployeeRoleId");

                    b.HasIndex("EmploymentStatusId");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("HRIS.Basic.Models.Domain.EmployeeAttendance", b =>
                {
                    b.Property<Guid>("EmployeeAttendanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IsActive")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TotalHours")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EmployeeAttendanceId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeAttendance", (string)null);
                });

            modelBuilder.Entity("HRIS.Basic.Models.Domain.EmployeeAttendanceLog", b =>
                {
                    b.Property<DateTime>("Checkin")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Checkout")
                        .HasColumnType("datetime");

                    b.Property<Guid>("EmployeeAttendanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeAttendanceLogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Location")
                        .HasColumnType("datetime");

                    b.HasIndex("EmployeeAttendanceId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeAttendanceLog", (string)null);
                });

            modelBuilder.Entity("HRIS.Basic.Models.Domain.EmployeeProjectAllocation", b =>
                {
                    b.Property<Guid>("EmployeeProjectAllocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("BillableHoursAssigned")
                        .HasColumnType("float");

                    b.Property<double>("BillableHoursWorked")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsBillable")
                        .HasColumnType("bit");

                    b.Property<double>("NonBillableHoursAssigned")
                        .HasColumnType("float");

                    b.Property<double>("NonBillableHoursWorked")
                        .HasColumnType("float");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EmployeeProjectAllocationId")
                        .HasName("PK_EmployeeProjectAllocation");

                    b.HasIndex("ProjectId");

                    b.ToTable("EmployeeProjectAllocation", (string)null);
                });

            modelBuilder.Entity("HRIS.Basic.Models.Domain.EmployeeRole", b =>
                {
                    b.Property<Guid>("EmployeeRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EmployeeRoleId");

                    b.ToTable("EmployeeRole", (string)null);
                });

            modelBuilder.Entity("HRIS.Basic.Models.Domain.EmployeeRoleAdditionalPermission", b =>
                {
                    b.Property<Guid>("EmployeeRoleAdditionalPermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EmployeeRoleAdditionalPermissionId");

                    b.ToTable("EmployeeRoleAdditionalPermission", (string)null);
                });

            modelBuilder.Entity("HRIS.Basic.Models.Domain.EmployeeRolePermission", b =>
                {
                    b.Property<Guid>("EmployeeRolePermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EmployeeRolePermissionId");

                    b.HasIndex("EmployeeRoleId");

                    b.ToTable("EmployeeRolePermission", (string)null);
                });

            modelBuilder.Entity("HRIS.Basic.Models.Domain.EmployeeSkill", b =>
                {
                    b.Property<Guid>("EmployeeSkillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EmployeeSkillId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("SkillId");

                    b.ToTable("EmployeeSkill", (string)null);
                });

            modelBuilder.Entity("HRIS.Basic.Models.Domain.EmploymentStatus", b =>
                {
                    b.Property<Guid>("EmploymentStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EmploymentStatusId");

                    b.ToTable("EmploymentStatus", (string)null);
                });

            modelBuilder.Entity("HRIS.Basic.Models.Domain.Job", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsBillable")
                        .HasColumnType("bit");

                    b.Property<Guid>("ReportTo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("JobId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Job", (string)null);
                });

            modelBuilder.Entity("HRIS.Basic.Models.Domain.Project", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProjectId");

                    b.ToTable("Project", (string)null);
                });

            modelBuilder.Entity("HRIS.Basic.Models.Domain.Skill", b =>
                {
                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SkillId");

                    b.ToTable("Skill", (string)null);
                });

            modelBuilder.Entity("HRIS.Basic.Models.Domain.SystemRole", b =>
                {
                    b.Property<Guid>("SystemRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SystemRoleId")
                        .HasName("PK_SystemRole");

                    b.ToTable("SystemRole", (string)null);
                });

            modelBuilder.Entity("HRIS.Basic.Models.Domain.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("SystemRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId")
                        .HasName("PK_User");

                    b.HasIndex("SystemRoleId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("HRIS.Basic.Models.Domain.Employee", b =>
                {
                    b.HasOne("HRIS.Basic.Models.Domain.EmployeeRole", "EmployeeRole")
                        .WithMany("Employees")
                        .HasForeignKey("EmployeeRoleId")
                        .IsRequired()
                        .HasConstraintName("FK_Employee_EmployeeRoleId");

                    b.HasOne("HRIS.Basic.Models.Domain.EmploymentStatus", "EmploymentStatus")
                        .WithMany("Employees")
                        .HasForeignKey("EmploymentStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Employee_EmploymentStatusId");

                    b.Navigation("EmployeeRole");

                    b.Navigation("EmploymentStatus");
                });

            modelBuilder.Entity("HRIS.Basic.Models.Domain.EmployeeAttendance", b =>
                {
                    b.HasOne("HRIS.Basic.Models.Domain.Employee", "Employee")
                        .WithMany("EmployeeAttendances")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK_EmployeeAttendance_EmployeeId");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRIS.Basic.Models.Domain.EmployeeAttendanceLog", b =>
                {
                    b.HasOne("HRIS.Basic.Models.Domain.EmployeeAttendance", "EmployeeAttendance")
                        .WithMany()
                        .HasForeignKey("EmployeeAttendanceId")
                        .IsRequired()
                        .HasConstraintName("FK_EmployeeAttendanceLog_EmployeeAttendanceId");

                    b.HasOne("HRIS.Basic.Models.Domain.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK_EmployeeAttendanceLog_EmployeeId");

                    b.Navigation("Employee");

                    b.Navigation("EmployeeAttendance");
                });

            modelBuilder.Entity("HRIS.Basic.Models.Domain.EmployeeProjectAllocation", b =>
                {
                    b.HasOne("HRIS.Basic.Models.Domain.Project", "Project")
                        .WithMany("EmployeeProjectsAllocations")
                        .HasForeignKey("ProjectId")
                        .IsRequired()
                        .HasConstraintName("FK_EmployeeProjectAllocation_EmployeeId");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("HRIS.Basic.Models.Domain.EmployeeRoleAdditionalPermission", b =>
                {
                    b.HasOne("HRIS.Basic.Models.Domain.Employee", "EmployeeRoleAdditionalPermissionNavigation")
                        .WithOne("EmployeeRoleAdditionalPermission")
                        .HasForeignKey("HRIS.Basic.Models.Domain.EmployeeRoleAdditionalPermission", "EmployeeRoleAdditionalPermissionId")
                        .IsRequired()
                        .HasConstraintName("FK_EmployeeRoleAdditionalPermission_EmployeeId");

                    b.Navigation("EmployeeRoleAdditionalPermissionNavigation");
                });

            modelBuilder.Entity("HRIS.Basic.Models.Domain.EmployeeRolePermission", b =>
                {
                    b.HasOne("HRIS.Basic.Models.Domain.EmployeeRole", "EmployeeRole")
                        .WithMany("EmployeeRolePermissions")
                        .HasForeignKey("EmployeeRoleId")
                        .IsRequired()
                        .HasConstraintName("FK_EmployeeRolePermission_EmployeeRoleId");

                    b.Navigation("EmployeeRole");
                });

            modelBuilder.Entity("HRIS.Basic.Models.Domain.EmployeeSkill", b =>
                {
                    b.HasOne("HRIS.Basic.Models.Domain.Employee", "Employee")
                        .WithMany("EmployeeSkills")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK_EmployeeSkill_EmployeeId");

                    b.HasOne("HRIS.Basic.Models.Domain.Skill", "Skill")
                        .WithMany("EmployeeSkills")
                        .HasForeignKey("SkillId")
                        .IsRequired()
                        .HasConstraintName("FK_EmployeeSkill_SkillId");

                    b.Navigation("Employee");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("HRIS.Basic.Models.Domain.Job", b =>
                {
                    b.HasOne("HRIS.Basic.Models.Domain.Employee", "Employee")
                        .WithMany("Jobs")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK_Job_EmployeeId");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRIS.Basic.Models.Domain.User", b =>
                {
                    b.HasOne("HRIS.Basic.Models.Domain.SystemRole", "SystemRole")
                        .WithMany("Users")
                        .HasForeignKey("SystemRoleId")
                        .IsRequired()
                        .HasConstraintName("FK_User_SystemRoleId");

                    b.Navigation("SystemRole");
                });

            modelBuilder.Entity("HRIS.Basic.Models.Domain.Employee", b =>
                {
                    b.Navigation("EmployeeAttendances");

                    b.Navigation("EmployeeRoleAdditionalPermission");

                    b.Navigation("EmployeeSkills");

                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("HRIS.Basic.Models.Domain.EmployeeRole", b =>
                {
                    b.Navigation("EmployeeRolePermissions");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("HRIS.Basic.Models.Domain.EmploymentStatus", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("HRIS.Basic.Models.Domain.Project", b =>
                {
                    b.Navigation("EmployeeProjectsAllocations");
                });

            modelBuilder.Entity("HRIS.Basic.Models.Domain.Skill", b =>
                {
                    b.Navigation("EmployeeSkills");
                });

            modelBuilder.Entity("HRIS.Basic.Models.Domain.SystemRole", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
